# PRODUCTOS

### Recuperar productos
GET http://155.210.71.196:1234/productos

### Recuperar un producto por ID
GET http://155.210.71.196:1234/productos/14f67968-b2b6-4fff-8f7e-636a4c001ce0

### Recuperar productos por categoría
GET http://155.210.71.196:1234/productos?categoria=Frutas

### Crear un producto
POST http://155.210.71.196:1234/productos
Content-Type: application/json

{
  "nombre": "Ejemplo 3",
  "descripcion": "Descripción del producto",
  "precio": 1.1,
  "stock": 60,
  "url_imagen": "https://example.com/imagen.jpg",
  "categoria": "Verduras"
}

### Eliminar un producto
DELETE http://155.210.71.196:1234/productos/d93f4996-3a4a-42cf-b456-544c29d53888

### Actualizar un producto
PATCH  http://155.210.71.196:1234/productos/d93f4996-3a4a-42cf-b456-544c29d53888
Content-Type: application/json

{
  "precio": 0.5
}


# USUARIOS

### Recuperar todos los usuarios
GET http://155.210.71.196:1234/usuarios

### Registrar un nuevo usuario
POST http://155.210.71.196:1234/usuarios/register
Content-Type: application/json

{
  "nombre": "Nuevo Usuario",
  "email": "b@b.com",
  "password": "1234567"
}

### Hacer login
POST http://155.210.71.196:1234/usuarios/login
Content-Type: application/json

{
  "email": "newuser@example.com",
  "password": "12345678"
}


# CARRITOS

### Obtener el carrito de un usuario
GET http://155.210.71.196:1234/carritos/1a2b3c4d
Authorization: Bearer TU_TOKEN_AQUI

### Añadir producto al carrito
POST http://155.210.71.196:1234/carritos/1a2b3c4d
Content-Type: application/json
Authorization: Bearer TU_TOKEN_AQUI

{
  "productoId": "0f24c493-212e-11f0-9e1d-00155dae7a67",
  "cantidad": 2
}

### Actualizar cantidad de producto en carrito
PATCH http://155.210.71.196:1234/carritos/1a2b3c4d/0f24c493-212e-11f0-9e1d-00155dae7a67
Content-Type: application/json
Authorization: Bearer TU_TOKEN_AQUI

{
  "cantidad": 4
}

### Eliminar un producto del carrito
DELETE http://155.210.71.196:1234/carritos/1a2b3c4d/0f24c493-212e-11f0-9e1d-00155dae7a67
Authorization: Bearer TU_TOKEN_AQUI

### Vaciar carrito
DELETE http://155.210.71.196:1234/carritos/1a2b3c4d
Authorization: Bearer TU_TOKEN_AQUI


# PEDIDOS

### Guardar un nuevo pedido
POST http://155.210.71.196:1234/pedidos
Content-Type: application/json
Authorization: Bearer TU_TOKEN_AQUI

{
  "usuario_id": "1a2b3c4d-5e6f-7g8h-9i10-abcdef123456",
  "productos": [
    {
      "id": "0f24c493-212e-11f0-9e1d-00155dae7a67",
      "cantidad": 3
    },
    {
      "id": "ab12cd34-5678-9ef0-1234-56789abcdef0",
      "cantidad": 1
    }
  ]
}